---
- name: Get Junos Device Facts
  hosts: vmx_devices
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  
  vars_prompt:
   - name: USERNAME
     prompt: User name
     private: no
   - name: DEVICE_PASSWORD
     prompt: Device password
     private: yes
     
  tasks:
   - name: Checking NETCONF connectivity
     wait_for: host={{ inventory_hostname }} port=22 timeout=5
     
   - name: Retrieve Junos OS Facts
     junos_get_facts:
       host={{ inventory_hostname }}
       user={{ USERNAME }}
       passwd={{ DEVICE_PASSWORD}}
     register: junos
       
   - name: Display Junos Facts
     debug: msg="Hostname:{{ junos.facts.hostname }}, Model:{{ junos.facts.model }}, Version:{{ junos.facts.version }}"
     
   
