---
- name: Issue Junos RPCs
  hosts: vmx_devices
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no
  
  vars_prompt:
   - name: USERNAME
     prompt: User name
     private: no
   - name: DEVICE_PASSWORD
     prompt: Device password
     private: yes
     
  tasks:
   - name: Get interfaces information
     junos_rpc:
       host={{inventory_hostname}}
       port=22
       user={{USERNAME}}
       passwd={{DEVICE_PASSWORD}}
       rpc=get-interface-information
       kwargs="terse=True"
       format=text
       dest=get_interface_information.conf
       
